### ISSUE TITLE
Feedback for “Quick Start”

### ISSUE THREAD

**Issue by Open-Source-Chivalry** [ahoylabs/faraday-guides#27]
你们的模型下载失败，说网络问题

**Comment by pacmanincarnate** [comment]
I'm not sure those are issues that are necessarily simple enough to write into the guide. Some issues need to have some back and forth to figure out and maybe more user-specific or version-specific.

**Comment by biw** [comment]
This issue isn't about the docs site, but rather an issue with the app. Please join us on Discord (https://faraday.dev/discord) and file a bug report there. Thank you!
